### ISSUE TITLE
Feature order cycle found... with terralith

### ISSUE THREAD

**Issue by kuronekotei** [Dekunutter/eastwardjourneys#1]
Exception generating new chunk
2 case 

java.lang.IllegalStateException: Feature order cycle found, involved sources:
    [Reference{ResourceKey[minecraft:worldgen/biome / terralith:fractured_savanna]
        =net.minecraft.world.level.biome.Biome@46bf77e2}
     , Reference{ResourceKey[minecraft:worldgen/biome / eastwardjourneys:old_growth_fir_forest]
        =net.minecraft.world.level.biome.Biome@16b62918}]

java.lang.IllegalStateException: Feature order cycle found, involved sources:
    [Reference{ResourceKey[minecraft:worldgen/biome / terralith:fractured_savanna]
        =net.minecraft.world.level.biome.Biome@7f5b9a83}
     , Reference{ResourceKey[minecraft:worldgen/biome / eastwardjourneys:hinoki_forest]
        =net.minecraft.world.level.biome.Biome@55301c55}]

if config
		hinokiBiomes = false
		waterFirBiomes = false
can generation

**Comment by Dekunutter** [comment]
Thanks for reporting this. Feature cycle orders typically mean the order in which biomes are loading their features are not consistent. Causes incompatibilities in many mods. Over the next few days I'll try to take a look into this and see if there's an easy fix I can patch in.

**Comment by Dekunutter** [comment]
This error has now been fixed in v1.0.2 of Eastward Journeys. Unfortunately there is still another feature order cycle issue with the latest version of Terralith but having browsed through biome feature ordering in vanilla Minecraft, the issue seems to lie with Terralith right now. [This issue ](https://github.com/Stardust-Labs-MC/Terralith/issues/42) is likely related.

I'm going to close out this issue as resolved, but will have to wait and see with the next version of Terralith if compatibility will be restored.
Let me know if you have any other issues!
