### ISSUE TITLE
make it compatible with village spawn point by serilum

### ISSUE THREAD

**Issue by Darklight-007** [Dekunutter/eastwardjourneys#6]
the title is enough i guess

**Comment by Dekunutter** [comment]
Not familiar with this mod, but from the description on CurseForge:

`Village Spawn Point is a minimalistic mod which sets the spawn point of a new world to always be in the center of a village. The village chosen will be the one closest to x=0, z=0.`

Seems to me that there's no way of configuring what villages are used for spawn, just whatever is closest to spawn. Also saw some mentions that the mod supports modded villages out of the box (probably since its just looking for any structures of the village type).

If you know otherwise, please let me know. Otherwise I don't think there's any action to take here!

**Comment by Darklight-007** [comment]
with another mod biome spawn point i can set the biome to spawn so with these 2 mods i can choose which type of village i wanna spawn in

**Comment by Darklight-007** [comment]
> Not familiar with this mod, but from the description on CurseForge:
> 
> `Village Spawn Point is a minimalistic mod which sets the spawn point of a new world to always be in the center of a village. The village chosen will be the one closest to x=0, z=0.`
> 
> Seems to me that there's no way of configuring what villages are used for spawn, just whatever is closest to spawn. Also saw some mentions that the mod supports modded villages out of the box (probably since its just looking for any structures of the village type).
> 
> If you know otherwise, please let me know. Otherwise I don't think there's any action to take here!

i tried so many times but it didnt seem to find ur village

**Comment by Darklight-007** [comment]
and another thing my mc client seems to crash when i try to join the server
can  u help?
nobody can find the issue 
[latest.log](https://github.com/Dekunutter/eastwardjourneys/files/12448468/latest.log)
[crash-2023-08-26_20.11.41-client.txt](https://github.com/Dekunutter/eastwardjourneys/files/12448470/crash-2023-08-26_20.11.41-client.txt)

[debug.log](https://github.com/Dekunutter/eastwardjourneys/files/12448469/debug.log)

**Comment by Darklight-007** [comment]
Dekunetter will u be resolving this?

**Comment by Dekunutter** [comment]
I'll close it out now since it sounds like you found a workaround, thanks!

**Comment by Darklight-007** [comment]
no. i didnt find a workaround. i think it is because the villages are rare. how can i change the rarity of the villages?
