### ISSUE TITLE
how to change rarity of villages?

### ISSUE THREAD

**Issue by Darklight-007** [Dekunutter/eastwardjourneys#7]

**Comment by Darklight-007** [comment]
it is not here

**Comment by Darklight-007** [comment]
I can't seem to find any villages. All other structures from mod i have found except the villages. @Dekunutter  check this for yourself

**Comment by Dekunutter** [comment]
Thanks, gonna try to take a look at this tonight. Pretty confident the villages are spawning correctly but they are rare since they only will spawn in the mod's own biomes and those biomes are kinda rare by design.

You may be able to locate one with a command if you have them enabled in your save. Something like `/locate structure eastwardjourneys:village_cherry_blossom` would find the nearest cherry blossom village type to your current position. If it returns no villages nearby, that would likely indicate that they are failing to spawn

**Comment by Dekunutter** [comment]
So I launched the mod and was able to find a village using the command I mentioned earlier. If you are looking to decrease the rarity of the village so its easier to come across, I have no means of configuring that in the mod right now. Could potentially be a future feature but there's no way of doing that in the current versions.

Going to close out this issue since I don't think there's any bug around this in the mod right now!

**Comment by Darklight-007** [comment]
It keeps saying structure not found nearby.

**Comment by Darklight-007** [comment]
I have tried locating it multiple times but i still can't find it

**Comment by Darklight-007** [comment]
@Dekunutter It doesnt seem to work for me

**Comment by Darklight-007** [comment]
![image](https://github.com/Dekunutter/eastwardjourneys/assets/89621633/6f970391-91a9-47f1-96e7-f2b9832ce1c6)
![image](https://github.com/Dekunutter/eastwardjourneys/assets/89621633/a923549c-c08c-4ad4-89f4-ced40e137543)
2 instances @Dekunutter

**Comment by Darklight-007** [comment]
only selects other villages

**Comment by Dekunutter** [comment]
I'm not sure if I'm following.

When you ran `/locate structure eastwardjourneys:village_cherry_blossom ` did you get any results? Or are you just trying to go to the nearest biome from the mod and hoping that the Village Spawn Point mod can find my village type?

May help as well if you can provide a debug log in pastebin or something, in case there is an issue.

**Comment by Darklight-007** [comment]
i did /locate but it didnt work it said no structures nearby. it only works when only eastward journeys is there in mods ffolder

are you just trying to go to the nearest biome from the mod and hoping that the Village Spawn Point mod can find my village type?
yes

**Comment by Dekunutter** [comment]
I'll need to see a full debug log to help any further I think (you can grab debug logs from the .minecraft/logs folder). When I had biome spawn point and eastward journeys both installed and I ran the /locate command it had no issues finding a village nearby. So I have not been able to find any issues.

Its possible there is a incompatibility with a different mod you are running, and its not a compatibility issue with biome spawn point

**Comment by Darklight-007** [comment]
[debug.log](https://github.com/Dekunutter/eastwardjourneys/files/12505351/debug.log)
[latest.log](https://github.com/Dekunutter/eastwardjourneys/files/12505352/latest.log)

**Comment by Dekunutter** [comment]
Thanks for providing the logs! I took a look at this tonight but unfortunately still not seeing any issue on my end. Tried installing a few more of the other mods you are using to see if there is an incompatibility but the cherry blossom village still generated successfully and I was able to find it using the `/locate structure` command.

**Comment by Darklight-007** [comment]
Maybe if you install all the mods and try , You may find the issue. If you want I can send you all the mods

**Comment by Darklight-007** [comment]
Hey Dekunutter did you find the issue?
